### ISSUE TITLE
[Bug]: Injected CSS不起作用

### ISSUE THREAD

**Issue by actforjason** [immersive-translate/immersive-translate#2233]
### 插件版本号 | Version

1.10.6

### 平台 | Platform

Windows

### 浏览器 | Browsers

Firefox

### 插件类型 | Extension Type

浏览器插件 | Browser Extension

### 请描述这个Bug | Describe the bug

修改字幕位置为固定不起作用：
```css
.imt-caption-window {
  position: fixed !important;
}
```

### 出现问题的网址 | URL

YouTube

### 补充说明 | Additional context
#1716
