### ISSUE TITLE
翻译后结果模糊是否可选百分比程度？

### ISSUE THREAD

**Issue by chNg1o** [immersive-translate/immersive-translate#355]
![image](https://user-images.githubusercontent.com/21314340/231766271-7ef03e83-5414-4ea7-ab2d-a959f505ea2a.png)
如果能自定义模糊程度就好啦

**Comment by versun** [comment]
@chNg1o 
这个功能以后可能会加上哈。
你可以先自己设置下，打开插件的**设置页面** -> 点击左边最下方的**开发者设置** -> 选择**Edit Injected CSS**
粘贴下方的代码，修改第二行的blur的值即可实现
```css
.immersive-translate-target-translation-theme-mask-inner {
  filter: blur(50%) !important;
  transition: filter 0.3s ease !important;
  border-radius: 10px;
}
```
