### ISSUE TITLE
希望增加透明效果

### ISSUE THREAD

**Issue by light4** [immersive-translate/immersive-translate#372]
### 您希望的更新和改进是什么 | Update or Improve

blur 看着晃眼睛，透明效果比较舒服，效果跟模糊类似，参考 #355 我目前自己设置了

打开插件的**设置页面** -> 点击左边最下方的**开发者设置** -> 选择 **Edit Injected CSS**

```css
.immersive-translate-target-translation-theme-mask-inner {
  filter: opacity(10%) !important;
  transition: filter 0.3s ease !important;
  border-radius: 10px;
}
```
